package registration;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import Booking.Room;

public class AdminDashboard extends JFrame {
    private JTable roomTable;
    private DefaultTableModel tableModel;
    private JButton addButton, editButton, deleteButton, refreshButton;
    private List<Room> rooms = new ArrayList<>();

    public AdminDashboard() {
        setTitle("Admin Dashboard - Room Management");
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        
        initUI();
        loadRoomData();
    }

    private void initUI() {
        JPanel mainPanel = new JPanel(new BorderLayout());
        
        // Table setup
        String[] columns = {"ID", "Number", "Type", "Price", "Status"};
        tableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Make table non-editable
            }
        };
        
        roomTable = new JTable(tableModel);
        roomTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        roomTable.getTableHeader().setReorderingAllowed(false);
        
        JScrollPane scrollPane = new JScrollPane(roomTable);
        mainPanel.add(scrollPane, BorderLayout.CENTER);
        
        // Button panel
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 10, 10));
        
        addButton = new JButton("Add Room");
        addButton.addActionListener(this::showAddRoomDialog);
        
        editButton = new JButton("Edit Room");
        editButton.addActionListener(this::showEditRoomDialog);
        
        deleteButton = new JButton("Delete Room");
        deleteButton.addActionListener(this::deleteRoom);
        
        refreshButton = new JButton("Refresh");
        refreshButton.addActionListener(e -> loadRoomData());
        
        buttonPanel.add(addButton);
        buttonPanel.add(editButton);
        buttonPanel.add(deleteButton);
        buttonPanel.add(refreshButton);
        
        mainPanel.add(buttonPanel, BorderLayout.SOUTH);
        add(mainPanel);
    }

    private void loadRoomData() {
        // Clear existing data
        tableModel.setRowCount(0);
        
        // In a real application, you would fetch this from your database
        // This is mock data for demonstration
        rooms.clear();
        rooms.add(new Room(5, "101", "DELUXE", 30.0, "AVAILABLE"));
        rooms.add(new Room(2, "102", "STANDARD", 100.0, "AVAILABLE"));
        rooms.add(new Room(4, "202", "DELUXE", 150.0, "AVAILABLE"));
        
        // Populate table
        for (Room room : rooms) {
            Object[] row = {
                room.getId(),
                room.getNumber(),
                room.getType(),
                room.getPrice(),
                room.getStatus()
            };
            tableModel.addRow(row);
        }
    }

    private void showAddRoomDialog(ActionEvent e) {
        JDialog dialog = new JDialog(this, "Add New Room", true);
        dialog.setSize(400, 300);
        dialog.setLayout(new GridLayout(5, 2, 10, 10));
        
        JTextField numberField = new JTextField();
        JComboBox<String> typeCombo = new JComboBox<>(new String[]{"STANDARD", "DELUXE", "SUITE"});
        JTextField priceField = new JTextField();
        JComboBox<String> statusCombo = new JComboBox<>(new String[]{"AVAILABLE", "OCCUPIED", "MAINTENANCE"});
        
        dialog.add(new JLabel("Room Number:"));
        dialog.add(numberField);
        dialog.add(new JLabel("Room Type:"));
        dialog.add(typeCombo);
        dialog.add(new JLabel("Price:"));
        dialog.add(priceField);
        dialog.add(new JLabel("Status:"));
        dialog.add(statusCombo);
        
        JButton saveButton = new JButton("Save");
        saveButton.addActionListener(ev -> {
            try {
                Room newRoom = new Room(
                    0, // ID will be generated by DB
                    numberField.getText(),
                    (String) typeCombo.getSelectedItem(),
                    Double.parseDouble(priceField.getText()),
                    (String) statusCombo.getSelectedItem()
                );
                
                // In real app: roomDAO.save(newRoom);
                rooms.add(newRoom);
                loadRoomData();
                dialog.dispose();
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(dialog, "Please enter a valid price", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });
        
        JButton cancelButton = new JButton("Cancel");
        cancelButton.addActionListener(ev -> dialog.dispose());
        
        dialog.add(saveButton);
        dialog.add(cancelButton);
        
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }

    private void showEditRoomDialog(ActionEvent e) {
        int selectedRow = roomTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a room to edit", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Room selectedRoom = rooms.get(selectedRow);
        
        JDialog dialog = new JDialog(this, "Edit Room", true);
        dialog.setSize(400, 300);
        dialog.setLayout(new GridLayout(5, 2, 10, 10));
        
        JTextField numberField = new JTextField(selectedRoom.getNumber());
        JComboBox<String> typeCombo = new JComboBox<>(new String[]{"STANDARD", "DELUXE", "SUITE"});
        typeCombo.setSelectedItem(selectedRoom.getType());
        JTextField priceField = new JTextField(String.valueOf(selectedRoom.getPrice()));
        JComboBox<String> statusCombo = new JComboBox<>(new String[]{"AVAILABLE", "OCCUPIED", "MAINTENANCE"});
        statusCombo.setSelectedItem(selectedRoom.getStatus());
        
        dialog.add(new JLabel("Room Number:"));
        dialog.add(numberField);
        dialog.add(new JLabel("Room Type:"));
        dialog.add(typeCombo);
        dialog.add(new JLabel("Price:"));
        dialog.add(priceField);
        dialog.add(new JLabel("Status:"));
        dialog.add(statusCombo);
        
        JButton saveButton = new JButton("Save");
        saveButton.addActionListener(ev -> {
            try {
                selectedRoom.setNumber(numberField.getText());
                selectedRoom.setType((String) typeCombo.getSelectedItem());
                selectedRoom.setPrice(Double.parseDouble(priceField.getText()));
                selectedRoom.setStatus((String) statusCombo.getSelectedItem());
                
                // In real app: roomDAO.update(selectedRoom);
                loadRoomData();
                dialog.dispose();
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(dialog, "Please enter a valid price", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });
        
        JButton cancelButton = new JButton("Cancel");
        cancelButton.addActionListener(ev -> dialog.dispose());
        
        dialog.add(saveButton);
        dialog.add(cancelButton);
        
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }

    private void deleteRoom(ActionEvent e) {
        int selectedRow = roomTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a room to delete", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this room?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
        );
        
        if (confirm == JOptionPane.YES_OPTION) {
            Room roomToDelete = rooms.get(selectedRow);
            // In real app: roomDAO.delete(roomToDelete.getId());
            rooms.remove(selectedRow);
            loadRoomData();
        }
    }
}